services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    command: serve
    volumes:
      - ntfy-cache:/var/cache/ntfy
      - ntfy-data:/var/lib/ntfy
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ntfy.rule=Host(`ntfy.pouic.cc`)"
      - "traefik.http.routers.ntfy.entrypoints=websecure"
      - "traefik.http.routers.ntfy.tls=true"
      - "traefik.http.routers.ntfy.tls.certresolver=letsencrypt"
      - "traefik.http.routers.ntfy.service=ntfy"
      - "traefik.http.services.ntfy.loadbalancer.server.port=80"

volumes:
  ntfy-cache:
  ntfy-data:

networks:
  traefik-net:
    external: true
