traefik-ovh-env: ENC[AES256_GCM,data:S64SsC6Wm6lrFg8H+t8U8wJQAosn8pKh0kJEXqA1fiJ0LTi+Sy6Ky/hfqACHUt0RCYTpj4HU9TyoeEg2CUHANX1NtYKEn2oJk1ubu5ewcPFCBs4r2kyUypPkH7yqYJnQgt3GecKpf31YKhqk7ba/Z0AGYgnnZ5oKzmwfQrmO5hWFML3iOvp0DlzxZVK41k1uO50DKURDC47iRI4pIIi5dQN4JQzGstxQ1AFV2ZpY7PX+UPAmq6YkbrxEO1suBBXkvVUw,iv:2l6qKjKXqHZXUanH5wQcWY+w3ZO6KFC+UcnkjnmN74g=,tag:7BEfYVPOy68lxgwKD8nZTw==,type:str]
sops:
    age:
        - recipient: age1yn39pts4aj9mcs6mgncw3cy409kdatamqaez2mgnh73vrqg98udq0slsnc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCV2cvdElUa3NJcWFiUG4w
            bGhNWjkvN0c0Z216eVlWTnd0bHFmdWlHLzMwCnhwWlNNSHRYNTU1d0VFWkI5L3N3
            aDZhTTF3bWtyREpJcHdCZllRckpZV0UKLS0tIFp5eFBLVm5DWEowQjd4N3FhS09h
            M2JGS1RndEtXRzc2V2RzOFE3Q2ltYkkKtXQu/QMkgTZkDJXw9CqF/XAd9Qdbqlkq
            k/xGPrB2O9M5qEICJCAEacfB453ZHAcnfHz7uh9NNkmf1umkXaaqvw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lrratr9lw0z7f5wlu8t8d6yepht3sxc8fy4y8xcq8pjzy6m273cq9r70m9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcXFHV1JOdGJCNlhCSUtU
            Q2NzT0VmSDlHNjJqYXd5NkRHVkdkTHpES0FZCkJNeHdBQ203a3ZuMVZzdHlRRXdD
            UWlmQ05VY2RCczZFUEl1T0hqQWVRSWMKLS0tIEpTYStxSFpELzZEUUhZN2hRUjdN
            eFpDcThDZVZKUGhleFBzSWR1NW5tMUkKPqkRnfaP18S8xav9Tx4q53FdAzNl50MV
            5yys8dd8xrG4sp+9cNn+C4/HmSui34+gIZPJ6G/BKumOLOLG2g/+hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-06T11:43:05Z"
    mac: ENC[AES256_GCM,data:0D6RQNT4xKgf122ElXN/L6r7j5RTWkekT0diFnntXwj0jp19GKEy4fKXtfcGzCYDqrBPM++Vc0lgz12K0+0Ugu4R/I+/2L1zmxTCYOjCp5EGJzrTieyF60yThsQA7bcw1JraSPfGC2YxDDBg49/LA3Hrgo51z6qDxzM+EcwllZw=,iv:tVblFeaYlpjrdWBCsmuFm1yleLmVn/yUV238dNCPC3g=,tag:s4MZph6DhvAIBj2W/tN36A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
